stages:
  - build
  - unitCases

basicBuildCase:
  stage: build
  script: 
    - cmake . 
    - make

unitCase1:
  stage: unitCases
  script:
    - cmake . 
    - make
    - ./road-generation test/test1.xml
    - cat test/test1.xodr
    - cat test/gt/test1.xodr
    - cmp --silent test/test1.xodr test/gt/test1.xodr && echo "succes"  || echo "no succes" 
    - cmp --silent test/test1.xodr test/gt/test1.xodr
  
unitCase2:
  stage: unitCases
  script:
    - cmake . 
    - make
    - ./road-generation test/test2.xml
    - cmp --silent test/test2.xodr test/gt/test2.xodr && exit 0 || exit 1

unitCase3:
  stage: unitCases
  script:
    - cmake . 
    - make
    - ./road-generation test/test3.xml
    - cmp --silent test/test3.xodr test/gt/test3.xodr && exit 0 || exit 1