name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true
    - name: Compile
      # Build your program with the given configuration
      run: |
           sudo apt install libxerces-c-dev
           mkdir -p build
           cd build
           rm -rf *
           cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../bin ..
           cmake --build .
           echo Compiled!
           
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: road-generation
          path: road-generation_exec
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
         name: road-generation
    - name: Run test
      run: |
        ls -la
        chmod +x road-generation_exec
        ./road-generation_exec -h

        
