name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true
    - name: Build
      # Build your program with the given configuration
      run: |
           sudo apt install libxerces-c-dev
           mkdir -p build
           cd build
           rm -rf *
           cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../bin ..
           cmake --build .
           echo Compiled!
    - name: Upload executable
      uses: actions/checkout@v2
      with:
        name: road-generation
        path: road-generation_exec
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: pwd
    - uses: actions/checkout@v2
      with:
         name: road-generation
        
