name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build executable
      run: |
            sudo apt install libxerces-c-dev
            mkdir -p build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../bin ..
            cmake --build .
            echo Compiled!
    - uses: actions/checkout@v2
      with:
        submodules: true
        name: road-generation
        path: road-generation_exec
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: ./road-generation_exec
    - uses: actions/checkout@v2
      with:
         name: road-generation
        
